### PR TITLE
feat: add Capacitor v3 support

### LINKED ISSUE #20: Update this plugin for Capacitor 3
Capacitor 3 is being built and is already in [beta](https://capacitorjs.com/blog/announcing-capacitor-3-0-beta). In this new version the native plugins have been removed from the core and there are some changes that are necessary in the existing plugins.

**Example: Plugin Imports**
The Plugins object is deprecated, but will continue to work in Capacitor 3. Capacitor plugins should be updated to use the new plugin registration APIs (see the Upgrade Guide for plugins), which will allow them to be imported directly from the plugin’s package.

Going forward, the Plugins object from @capacitor/core should not be used.

```
// OLD
import { Plugins } from '@capacitor/core';
const { AnyPlugin } = Plugins;
Importing the plugin directly from the plugin’s package is preferred, but the plugin must be updated to work with Capacitor 3 for this to be possible.
```

```
// NEW
import { AnyPlugin } from 'any-plugin';
```

**References:**

[Updating Capacitor to 3.0 in your plugin](https://capacitorjs.com/docs/v3/updating/plugins/3-0)

[Updating Capacitor to 3.0 in your app](https://capacitorjs.com/docs/v3/updating/3-0)

### PR DESCRIPTION
**Pull request by vitorlopez**
Closes #20

I did a few changes to make this plugin to work with Capacitor 3.

I think there's probably somethings left to do, but it seems like it's working so far, I'd love some feedbacks about this.

### CODE REVIEW

**Comment by robingenz** [comment]
Thank you for your contribution. Your changes look good. 
I would like to fix all open bugs before updating to Capacitor 3, so that users with Capacitor 2 are not forced to update. 
As soon as all open bugs are fixed, I will merge this PR.

**Comment by vitorlopez** [comment]
Awesome! Yea this is a good point. Let me know if you need any help with the changes for that.

**Comment by robingenz** [comment]
@vitorlopez Can you please resolve the merge conflicts?

**Review by robingenz — APPROVED** [review]

**Comment by robingenz** [comment]
@vitorlopez Thank you for your contribution!

**Pull request merged**
